---
title: "R Notebook"
output: html_notebook
---

```{r}

library(tidyverse)
library(janitor)
library(cluster)
library(factoextra)
library(dendextend)
library(corrplot)
library(skimr)

```

```{r}

edu_data <- read_csv("data/school_data.csv") %>% 
  clean_names()

edu_data

```

```{r}

edu_data %>% 
  skim()

```

```{r}

edu_data <- edu_data %>% 
  column_to_rownames("x1")



```

Rescale numerics to be standard normal, so the units don#t affect distance measure

```{r}

edu_data_scaled <- edu_data %>% 
  mutate(across(.fns = scale))

skim(edu_data_scaled)

```

```{r}

edu_data_scaled %>% 
  cor() %>% 
  corrplot(method = "number", type = "lower")

# other way to achieve a similar output
GGally::ggcorr(edu_data_scaled)

```

Calculate distance measure, make a dissimilarity matrix

```{r}

diss_matrix <- edu_data_scaled %>% 
  select(home_school) %>% 
  dist(method = "euclidean")

```

```{r}

fviz_dist(diss_matrix)

```
For a single variable the distance is the absolute difference in the values.
i.e. sqrt((x2 - x1)^2) = x2 - x1



```{r}

max(edu_data_scaled$home_school) # max = 2.2
min(edu_data_scaled$home_school) # min = -1.6

# range = 2.2 - (-1.6) = 3.8

```

```{r}

clusters <- diss_matrix %>% 
  hclust(method = "complete")

```

```{r}

clusters %>% 
  plot(cex = 0.5,
       hang = -5)

```

```{r}

alt_clusters <- diss_matrix %>% 
  hclust(method = "ward.D2")

```

```{r}

clustering_dendrogram <- clusters %>% 
  as.dendrogram() %>% 
  dendextend::set("labels_cex", 0.5)

clustering_dendrogram

```

```{r}

alt_clustering_dendrogram <- alt_clusters %>% 
  as.dendrogram() %>% 
  dendextend::set("labels_cex", 0.6)

alt_clustering_dendrogram

```

```{r}

dend_diff(clustering_dendrogram, alt_clustering_dendrogram)

```

```{r}

plot(clusters, cex = 0.6, hang = -1)
rect.hclust(clusters, k = 4, border = 2:5)

```

