---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

# Defining input data - money spent and category of expense
amount_spent <- c(9.1, 8.55, 14.32, 14.17, 14.34, 7.97, 9.79, 11.47, 12.44)
category <- c("Lunch", "Dinner", "Lunch", "Lunch", "Cinema", "Drinks", "Lunch",
              "Lunch", "Dinner")

# Joining both sets of data above into a single tibble
my_week_of_spending <- tibble(
  amount_spent = amount_spent,
  spending_category = category)

# Calculating total amount spent in the week
my_week_of_spending %>% 
  summarise(sum(amount_spent))

# Calculating total amount spent on "Lunch" in the week
my_week_of_spending %>% 
  filter(spending_category == "Lunch") %>% 
  summarise(sum(amount_spent))


```

```{r}

AmountSpent <- c(9.1, 8.55, 14.32, 14.17, 14.34, 7.97, 9.79, 11.47, 12.44)
Category <- c(
  "Lunch",
  "Dinner",
  "Lunch",
  "Lunch",
  "Cinema",
  "Drinks",
  "Lunch",
  "Lunch",
  "Dinner"
)
my.week.of.spending <- tibble(AmountSpent = AmountSpent, SpendingCategory = Category)
str(my.week.of.spending)
View(my.week.of.spending)
my.week.of.spending
summarise(my.week.of.spending, sum(AmountSpent))
summarise(filter(my.week.of.spending, SpendingCategory == "Lunch"), sum(AmountSpent))



```


